### ISSUE TITLE
Reduce the number of dependencies

### ISSUE THREAD

**Issue by kokes** [aws/amazon-redshift-python-driver#10]
## Driver version
2.0.405

## Problem description

For a database driver, this library has a number of some fairly large dependencies. From what I can tell, `numpy` and `pandas` are only being used in a handful of methods, they are not core to the library, so they could easily be optional dependencies. That would reduce the load and installation issues quite substantially. A case could be made for some of the other dependencies (where one could e.g. specify their credentials provider to load some extra dependencies).

All of this could be achieved through extras and some conditional importing.

**Comment by Brooke-white** [comment]
Hey @kokes,

Good point -`numpy` and `pandas` are used in just a handful of functions and could easily be changed to be optional dependencies, so everyone isn't forced to install them :). Thanks for taking a look & providing this feedback! I'll provide an update here once the change is in.

--brooke

**Comment by Brooke-white** [comment]
Hey @kokes,

We have made `numpy` and `pandas` optional dependencies as of release [v2.0.659](https://github.com/aws/amazon-redshift-python-driver/tree/v2.0.659), thanks again for your feedback :)
