### ISSUE TITLE
IAM authentication leads to unclosed socket warning

### ISSUE THREAD

**Issue by Tradunsky** [aws/amazon-redshift-python-driver#100]
## Driver version

^2.0.907

## Redshift version

'                                             version
'PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.38094��'

## Client Operating System

Darwin Kernel Version 20.6.0

## Python version
3.7, 3.9

## Problem description
Execution of a simple sample leads to unclosed socket warning:

1. Expected behaviour: All sockets closed
2. Actual behaviour: Seems like a memory leak
3. Error message/stack trace:
```python
/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py:1264: ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('...', 56127), raddr=('...', 443)>
  return list(_active.values()) + list(_limbo.values())
Object allocated at (most recent call last):
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", lineno 833
    self = cls.__new__(cls, **kwargs)
```
```python
.venv/lib/python3.9/site-packages/redshift_connector/iam_helper.py:131: ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('....', 60344), raddr=('...', 443)>
  IamHelper.set_cluster_credentials(provider, info)
Object allocated at (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", lineno 1003
    self = cls.__new__(cls, **kwargs)
```
4. Any other details that can be helpful:
There is no such error when setting `iam=False`.

## Reproduction code

```python
with redshift_connector.connect(
            iam=True,
            database=REDSHIFT_DATABASE,
            db_user=REDSHIFT_DB_USER,
            cluster_identifier=REDSHIFT_CLUSTER_IDENTIFIER,
            region=DATASOURCE_AWS_REGION,
            profile=DATASOURCE_AWS_PROFILE,
            timeout=self.timeout_sec
        ) as connection, connection.cursor() as cursor:
    cursor.execute("SELECT 1")
    return cursor.fetch_dataframe()
```

**Comment by Brooke-white** [comment]
I am able to reproduce after adding the following at the top of the `Reproduction code`

```
import warnings
warnings.simplefilter('always')
```

I looked around a bit and found [this issue open with boto3](https://github.com/boto/boto3/issues/454), which looks like where the error is originating from. As I said earlier, redshift-connector doesn't directly open any sockets in the mentioned block of code, [set_cluster_credentials](https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/iam_helper.py#L174), we invoke boto3 which appears to be doing so.

Unfortunately we cannot suppress warnings from libraries redshift-connector uses, but the mentioned issue above gives a good overview of why this message shows up as well as some different thoughts on it.

Please let me know if you have any other questions or need clarification

**Comment by Tradunsky** [comment]
Hi @Brooke-white,

Sorry for the late reply, was away from the keyboard for some time.

Thank you very much for the reference! I have read some workarounds, like suppressing the warning and also spent a decent amount of time debugging redshift connector itself, before submission of this issue, but I have not realized the depth of the issue actually related to boto3 and not the usage of boto3 by readshift connector. Thank you for pointing this out!

However, according to the most likely solution boto3 maintainers accept https://github.com/boto/botocore/pull/1810 (of course after some analysis) do you think redshift connector maintainers should make a change in the connector to prevent this memory leak from happening?
<img width="987" alt="image" src="https://user-images.githubusercontent.com/4522842/169630653-78cfdd01-caab-4843-b263-7b22dfe70bf2.png">

**Comment by Brooke-white** [comment]
Hey @Tradunsky , thanks for following up. We can monitor the referenced solution, and if merged, take steps to apply to redshift_connector as well.
