### ISSUE TITLE
If no username / password is given, get it from `pgpass`

### ISSUE THREAD

**Issue by dannysepler** [aws/amazon-redshift-python-driver#103]
## Driver version
2.0.907

## Redshift version
`('PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.38551')`

## Client Operating System
Mac OSX

## Python version
Py3.10

## Table schema
N/A

## Problem description
In `psycopg2`, if no username / password is given, the package will infer it from a user's pgpass. But in this package, the pgpass is not respected.

## Reproduction code
```python
import psycopg2
import redshift_connector

def no_pass_psycopg2():
    """ This works """
    conn = psycopg2.connect(f"dbname='{DB}' user='{USER}' host='{HOST}' port='5439'")

    cursor = conn.cursor()
    cursor.execute("SELECT 1;")
    print(cursor.fetchall())


def no_pass_redshift_connector():
    """ This fails """
    conn = redshift_connector.connect(host=HOST, database=DB, user=USER)

    cursor = conn.cursor()
    cursor.execute("SELECT 1;")

    print(cursor.fetchall())
```

The second one fails on: `redshift_connector.error.InterfaceError: {'S': 'FATAL', 'C': '28000', 'M': 'password authentication failed for user "<my username>"', 'F': '../src/pg/src/backend/libpq/auth.c', 'L': '418', 'R': 'auth_failed'}` -- it's interesting that it mentions `libpq` because `libpq` explicitly has support for the pgpass https://www.postgresql.org/docs/current/libpq-pgpass.html

**Comment by Brooke-white** [comment]
Hey @dannysepler, thanks for reaching out with this feature request. I will chat with the Redshift driver team and provide an update here.
