### ISSUE TITLE
Mismatch between requirements.txt and setup.py

### ISSUE THREAD

**Issue by kokes** [aws/amazon-redshift-python-driver#11]
## Driver version
2.0.405

## Problem description

There's quite a strict requirement for pandas in setup.py (`==0.25.3`), but I see a looser one in requirements.txt (`>=0.25.3<1.1.0`). This poses two problems:

1. One then cannot quite pinpoint what the requirement really is and why it differs in these two places.
2. The library unnecessarily depends on an old version of pandas (v1.0 was released earlier this year) without really requiring any of its old functionality.

I would propose joining the two mechanisms together - perhaps loading requirements.txt programatically into setup.py, splitting the reqs along the way into runtime dependencies and development dependencies.

**Comment by Brooke-white** [comment]
Hey @kokes,

Thank you for your feedback. 

1. I agree that moving all requirements to `setup.py` would simplify things on all fronts.
2.  The strict requirement on pandas `==0.25.3` in `requirements.txt` is incorrect, and what's specified in `setup.py`, `>=0.25.3<1.1.0`, is correct. 

I'll open a ticket in our internal tracking system to address these two issues and will post an update here once the change has been made.

--brooke

**Comment by mirosval** [comment]
Is there a reason for the `<1.1.0` bit? Pandas added support for Python 3.9 in 1.1.3 so as it is, this repo is not 3.9 compatible because of this (at least)

**Comment by Brooke-white** [comment]
Hey @mirosval ,

We will be making `pandas` and `numpy` optional requirements with the next release, and remove the strict version requirements. The next release is planned for this coming Monday, November 23.

The `<1.1.0` bit is just outdated. I ran through our build and test suite with `Python 3.9` and `pandas-1.1.4` and am not seeing any issues at this time.

**Comment by Brooke-white** [comment]
Hi all,

We've addressed the versioning mis-match for `pandas` - and made both `pandas` and `numpy` optional dependencies. The strict version requirements for those packages has been removed for now as well, given the use of these packages is limit at this time. These changes are in release [v2.0.659](https://github.com/aws/amazon-redshift-python-driver/tree/v2.0.659)
