### ISSUE TITLE
Is there some kind of mapping a data type's oid to its name?

### ISSUE THREAD

**Issue by ni-todo-spot** [aws/amazon-redshift-python-driver#111]
## Driver version
2.0.905

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.36224��

## Client Operating System
Darwin Nativs-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

## Python version
3.8.7

## Problem description
I was wondering if there is some  a way for to convert a data type `type_oid` into string instead.

```python
cursor.execute("SELECT int_col from some_table")
description = cursor.description
oid = description[0][1]
print(oid)  # will print oid. for the sake of example let's say it's 1
print(some_func(oid)). # "int"
```
 in psycopg2 there is the https://www.psycopg.org/docs/extensions.html#psycopg2.extensions.string_types

so I'm looking for something similar, but for redshift data types.

Thanks in advance!

**Comment by Brooke-white** [comment]
Hey @ni-todo-spot ,

Thanks for reaching out. We don't currently have an equivalent to psycopg2's `string_types`, the best I could point you towards is the projects `type_utils.py` file, where a mostly complete list of OIDs supported by redshift_connector can be found. Though I'm not sure how useful this will be for you in its current form.

The list of supported OIDs are made available on a module level as they're used by tools that consume redshift_connector such as sqlalchemy, so we'd still need to provide this if we work to provide the functionality given by`string_types`.

I will take a look into work required for adding this feature, and get back to you shortly :)

**Comment by Brooke-white** [comment]
Hi @ni-todo-spot 

I looked into `string_types` a bit more and it looks like it can also be used for [defining new datatypes and associated converters](https://stackoverflow.com/questions/52484070/psycopg2-type-caster-is-created-and-registered-but-not-found). Not sure if you're interested in this functionality, but **it is** supported by redshift_connector. You can add/modify datatype converter functions using `type_utils.py`.

**IN** functions (data received from Redshift): https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/utils/type_utils.py#L640

**OUT** functions (data sent to Redshift): https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/utils/type_utils.py#L726

**Comment by ni-todo-spot** [comment]
@Brooke-white Thanks for your quick reply!

Regarding your second comment - I'm not sure it's good idea to mix postgres & redshift data types together.

For now I made a n `oid_to_name` map in my specific case. It's not ideal but for my purposes it's good enough. If you think it's worth it I can submit a PR with it so it would be public.

I hope a better solution can be implemented soon (and it would be easy to 😅 ).

 Thanks a lot 😄

**Comment by ni-todo-spot** [comment]
@Brooke-white Wow that would be amazing!
We are definitely going to use this 😃 

Thank you very much 👏

**Comment by Brooke-white** [comment]
Hi @ni-todo-spot -- we've just released v2.0.908 which includes support for this feature as noted above.

```
from redshift_connector.utils.oids import get_datatype_name
get_datatype_name(1266)
Out[3]: 'TIMETZ'
get_datatype_name(23)
Out[4]: 'INTEGER'
```

I'll be closing this issue but feel free to open a new one if you see any issue with this feature or need any help. Thanks again for working with us to improve redshift-connector! :)

**Comment by ni-todo-spot** [comment]
@Brooke-white SUPER!
Thank you very much for your quick response :)
We'll definitely going to use this feature!

**Comment by alonme** [comment]
Hey @Brooke-white,

I noticed that the OID `1043` and `22` have 2 representation in the Enum

[1034 related code](https://github.com/aws/amazon-redshift-python-driver/blob/26fc02dd860a31daf31b92b4ccf1ef66a09f3cdf/redshift_connector/utils/oids.py#L62-L76).


This means that when using `get_datatype_name` the result will always be the first one of them,
and in the case of `1043` the result is `STRING`, which doesn't seem to be a "real" type in redshift?
for instance i can't cast to `STRING` but i can cast to `VARCHAR` (which is the other value for 1043)


Can you please help and explain the reason?
