### ISSUE TITLE
get_columns for tablename with surrounding 'single quotes'

### ISSUE THREAD

**Issue by janyewest** [aws/amazon-redshift-python-driver#117]
redshift_connector cursor.get_columns() is not able to find my table which is named 'some_table' (WITH the surrounding single quotes.)

What can I do? thank you.

**Comment by Brooke-white** [comment]
Hey @janyewest , could you please provide the information requested in the issue template such as a code snippit and redshift_connector version so we can better assist you? 

In the meantime, I'd recommend to look at the [source code for get_columns()](https://github.com/aws/amazon-redshift-python-driver/blob/80c416bde2192ebce23e075247937fa12bc8ccfa/redshift_connector/cursor.py#L1102) to self confirm you're using it as intended.
