### ISSUE TITLE
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives

### ISSUE THREAD

**Issue by ad-m-ss** [aws/amazon-redshift-python-driver#122]
## Driver version

Apply to master too.

## Redshift version

N/A

## Client Operating System

N/A
## Python version

3.10

## Table schema

N/A
## Problem description

Library raises deprecation warning:

```
  /usr/local/lib/python3.10/site-packages/redshift_connector/core.py:10: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion
```

## Reproduction code

Just import connector

**Comment by Brooke-white** [comment]
Hey @ad-m-ss , thanks for the heads up about this. we will work to fix in next release.

**Comment by Brooke-white** [comment]
[2.0.909](https://github.com/aws/amazon-redshift-python-driver/releases/tag/v2.0.909) has been released with this fix.
