### ISSUE TITLE
Disable  prepared statement?

### ISSUE THREAD

**Issue by 65usami** [aws/amazon-redshift-python-driver#13]
## Driver version
2.0.405

## Python version
3.8.3

## Problem description
I got this error when I execute multiple queries.

```
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    exec_transaction(query)
  File "main.py", line 53, in exec_transaction
    cur.execute(query)
  File ".../lib/python3.8/site-packages/redshift_connector/cursor.py", line 154, in execute
    self._c.execute(self, operation, args)
  File ".../lib/python3.8/site-packages/redshift_connector/core.py", line 984, in execute
    self.handle_messages(cursor)
  File ".../lib/python3.8/site-packages/redshift_connector/core.py", line 1140, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'cannot insert multiple commands into a prepared statement', 'F': '/home/ec2-user/padb/src/pg/src/backend/tcop/postgres.c', 'L': '2619', 'R': 'exec_parse_message'}
```

Is it possible to disable  prepared statement?
I want to execute multiple queries at one cursor.

```
query = """\
  CREATE TEMP TABLE temp_cate
  (
    class_code        INTEGER NULL,
    class_name        VARCHAR(255) NULL
  );
  copy temp_cate from 's3://{aws_s3_path}'
  credentials 'aws_access_key_id={aws_access_key};aws_secret_access_key={aws_secret_access_key}'
  csv;

  delete from d_class2 where class2_code in (select class_code from temp_cate);

  insert into d_class2 (
    select
      class2_code,
      class2_name,
      SYSDATE
    from temp_cate
  );
"""

with redshift_connector.connect(**params) as con:
  with con.cursor() as cur:
    cur.execute(query)
```

**Comment by Brooke-white** [comment]
Hi @65usami ,

Could you clarify what you mean by "execute multiple queries at one cursor"?

Per https://www.python.org/dev/peps/pep-0249/#id15, the `execute(...)` method executes a single database operation. `execute_many(...)` can be used for multiple database operations, though I'm not sure it fits the use case described in your code snippit. See https://www.python.org/dev/peps/pep-0249/#executemany for more details.

redshift_connector does not currently offer the ability to disable prepared statement.

If you are looking to execute multiple queries **using a single connection**, you could do as follows

```python
sql_stmts: typing.List[str] = [
  'create table ...',
  'copy ...',
  'delete ...',
  ...
]
with redshift_connector.connect(**params) as con:
  with con.cursor() as cur:
    for stmt in sql_stmts:
      cur.execute(query)
```

**Comment by Brooke-white** [comment]
Closing as no response received, please re-open if you have more to add.

**Comment by 65usami** [comment]
Sorry late reply.
I understood your answer and Thank you very much your advice.
I will follow your advice.
