### ISSUE TITLE
Publish new release to ease constraints on deps

### ISSUE THREAD

**Issue by domcorvasce** [aws/amazon-redshift-python-driver#131]
## Problem description

The latest version of the module (`2.0.908`) has strict constraints on the `requests` module (see https://github.com/aws/amazon-redshift-python-driver/issues/118). I see the constraints have already been eased and the changes have been merged on `master`. Would it be possible to publish a new version of this module?

**Comment by Brooke-white** [comment]
Hi @domcorvasce , apologies for the delay in releasing. we are planning to release early October. If this is a blocker for you please advise and we can work to expedite the release.

**Comment by domcorvasce** [comment]
> Hi @domcorvasce , apologies for the delay in releasing. we are planning to release early October. If this is a blocker for you please advise and we can work to expedite the release.

Thanks @Brooke-white! It would be great if you could expedite the release since we really need to use this library but in the meantime the “workaround” is installing the module directly from the GitHub repo.

**Comment by Brooke-white** [comment]
@domcorvasce , thank you for sharing this. I'll work to expedite the release. There's one remaining issue, #127, I'm hoping to wrap up work on so we can fit in this release. Once I make that change I'll release ASAP. Thank you for your patience :)

**Comment by Brooke-white** [comment]
@domcorvasce , we just released v2.0.909 of redshift_connector. You should be unblocked now :) . I will update the project GitHub so you may view the changelog shortly.

**Comment by Brooke-white** [comment]
[2.0.909](https://github.com/aws/amazon-redshift-python-driver/releases/tag/v2.0.909) has been released with this fix.
