### ISSUE TITLE
Understanding write_dataframe : unpack_from requires a buffer error...

### ISSUE THREAD

**Issue by ian-grover** [aws/amazon-redshift-python-driver#142]
Hi

I am making use of the redshift connector with the write_dataframe function. I have two databases, one for testing and one for production. My test database is working fine but my production one is returning an error
```cursor.write_dataframe(df, redshift_table)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/cursor.py", line 584, in write_dataframe
    self.executemany(sql, arrays)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/cursor.py", line 266, in executemany
    self.execute(operation, parameters)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/cursor.py", line 240, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/core.py", line 1783, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/core.py", line 1965, in handle_messages
    code, data_len = ci_unpack(self._read(5))
struct.error: unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)
```

From what I understand, there should not be any difference in settings between the two databases, but there is clearly something happening in one than the other. The docker image being used is identical in the two jobs. 

Does anyone here have any experience with what generates this error and where I should be looking to address and fix it?

**Comment by Brooke-white** [comment]
Hey @ian-grover , could you share the Redshift server versions of your Prod and testing clusters?

**Comment by ShumzZzZz** [comment]
Is there any update on this?

I submitted a Sklearn or Pyspark processing job to AWS SageMaker; inside the job, I used redshfit_connector to query (simple select, nothing fancy) some tables (it could happen to any table, not any specific table). With the exact same code and no changes made to the queried tables, this job could fail with the same error msg:

....
File "/usr/local/lib/python3.9/site-packages/redshift_connector/cursor.py", line 229, in execute
    self._c.execute(self, "begin transaction", None)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/core.py", line 1718, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/core.py", line 1982, in handle_messages
    code, data_len = ci_unpack(self._read(5))
struct.error: unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)

**Comment by Brooke-white** [comment]
Hey @ShumzZzZz -- this issue can occur for a number of reasons. I am working with the Redshift server team to investigate this issue and will update here as I can. if you can provide the Redshift server version and whether you're using Redshift provisioned or serverless it can help aid this investigation.

**Comment by ori-maci** [comment]
Hello @Brooke-white is there any update or insight on how to fix this issue? I am encountering the same issue and here is my version: 

`redshift-connector = "^2.0.910"`

**Comment by sr-murthy** [comment]
Unfortunately I have the same issue. Running a Panoply query for a sizable dataset (of around 200 MB) in iPython using `redshift_connector` gives me:
```
struct.error: unpack_from requires a buffer of at least 46 bytes for unpacking 4 bytes at offset 42 (actual buffer size is 29)
```
This was after using `client_protocol_version=0` in the call. I'm using Python 3.9.6 and iPython 8.13.2, on a MacBook Pro (mid 2020, Intel i7, MacOS Ventura 13.3.1 (a)).

**Comment by sr-murthy** [comment]
@ori-maci I've been able to work around the problem by using [sqlalchemy-redshift](https://pypi.org/project/sqlalchemy-redshift/), which I believe allows you to create and use a SQL Alchemy engine with the Redshift driver and dialect.
```
import sqlalchemy as sa
from sqlalchemy.engine.url import URL

engine = sa.create_engine(URL.create(host=<host>,
                                     drivername='redshift+redshift_connector',
                                     database=<database>,
                                     username=<username>,
                                     password=<password>,
                                     port=<port>,
                                     **kwargs))

with engine.connect() as conn:
    return pd.DataFrame(conn.execute(...).fetchall())
...
```

**Comment by Brooke-white** [comment]
Hi all, the team recommends the following
- ensure Redshift cluster software is up to date
- if issue persists, use of sqlalchemy or connection pooler
