### ISSUE TITLE
Print/get DataFrame from RAISE displayed in Messages

### ISSUE THREAD

**Issue by marcin2x4** [aws/amazon-redshift-python-driver#143]
## Driver version
Latest

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.44903

## Client Operating System
WSL2/Win10

## Python version
3.9

## Problem description
To not save result into temp table I want to catch it on the fly but can't find best approach to achieve it. Didn't find and good method in `redshift_connector` and `boto3`.

It seems that Redshift doesn't support [DO](https://www.postgresql.org/docs/current/sql-do.html)

I could query `svl_stored_proc_messages` but I don't want any in-the-middle steps...

Goal is to get dataFrame that would have data from `Messages`:
![obraz](https://user-images.githubusercontent.com/71531928/217672386-cf900b1e-cbea-4789-bfa4-dbb290db97dd.png)

## Reproduction code
Procedure:

```
CREATE OR REPLACE PROCEDURE public.record_example()
AS '
DECLARE
  rec RECORD;
BEGIN
  FOR rec IN SELECT * FROM public.event
  LOOP
    RAISE INFO ''eventid = %'', rec.eventid;
  END LOOP;
END;
'
LANGUAGE plpgsql;
```

Python code:
```
import redshift_connector

conn = redshift_connector.connect(
    host='xyz-cluster.abc.region.redshift.amazonaws.com',
    database='',
    user='',
    password=''
 )

cursor = conn.cursor()
cur = cursor.execute("CALL public.record_example();")
```

**Comment by Brooke-white** [comment]
Hi @marcin2x4 , I am lacking some understanding of this issue and I am not entirely sure this is something that can be addressed by client tools like redshift-connector or boto3. Redshift client tools can only utilize the existing functionality of Redshift server. Is a [UDF](https://docs.aws.amazon.com/redshift/latest/dg/udf-python-language-support.html) applicable to your use case? 

If you can explain more about your use case I can try to assist further or route this request to the correct Redshift team, if needed.

**Comment by marcin2x4** [comment]
@Brooke-white - I did find a workaround for this. Will post it soon for reference with explanation on 'why'.

**Comment by marcin2x4** [comment]
@Brooke-white - goal was to capture data from stored procedure without table/temp table. Below are code samples I've managed to come up with. This works only on multi-node Redshift cluster.

```
CREATE OR REPLACE PROCEDURE schema.sp_data_on_fly(rs_out INOUT refcursor)
LANGUAGE plpgsql
AS $$
BEGIN
    OPEN rs_out FOR SELECT * FROM (SELECT...);
END;
$$
```

Once ready, these lines below with execute the code in synchronous manner.
```
cursor.execute("CALL reporting.sp_data_on_fly('mycursor');")
cursor.execute("FETCH ALL FROM mycursor;")
```
