### ISSUE TITLE
redshift-connector: required db_groups with Okta as an identity provider from Jupyter notebook

### ISSUE THREAD

**Issue by selvathiruarul** [aws/amazon-redshift-python-driver#145]
## Driver version
2.1.0.10

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.44679
## Client Operating System
macOS  13.2 (22D49)

## Python version
3.9.6

## Problem description
Hi, I tried to connect to redshift from Jupyter notebook using redshift-connector by following the steps in 
https://aws.amazon.com/blogs/big-data/federated-api-access-to-amazon-redshift-using-an-amazon-redshift-connector-for-python/
But it errored out without specifying the db_groups parameter. It works with the db_groups parameter. The end user doesn't necessarily have to know the db_group to connect. 

## Python Driver trace logs
ClientError                               Traceback (most recent call last)
Cell In[15], line 5
      2 import numpy
      4 # Connects to Redshift cluster using Okta MFA Browser Plugin
----> 5 conn = redshift_connector.connect(
      6     iam=True,
      7     host='{host_name}',
      8     port=5439,
      9     database='{dbname}',
     10     db_user='{username}',
     11     cluster_identifier='{cluster_id}',
     12     region='us-east-1',
     13     login_url='{login_url}',
     14     credentials_provider='BrowserSamlCredentialsProvider',
     15     password=''
     16 )

File ~/Library/Python/3.9/lib/python/site-packages/redshift_connector/__init__.py:332, in connect(user, database, password, port, host, source_address, unix_sock, ssl, sslmode, timeout, max_prepared_statements, tcp_keepalive, application_name, replication, idp_host, db_user, app_id, app_name, preferred_role, principal_arn, access_key_id, secret_access_key, session_token, profile, credentials_provider, region, cluster_identifier, iam, client_id, idp_tenant, client_secret, partner_sp_id, idp_response_timeout, listen_port, login_url, auto_create, db_groups, force_lowercase, allow_db_user_override, client_protocol_version, database_metadata_current_db_only, ssl_insecure, web_identity_token, role_session_name, role_arn, iam_disable_cache, auth_profile, endpoint_url, provider_name, scope, numeric_to_float, is_serverless, serverless_acct_id, serverless_work_group, group_federation)
    329         _logger.debug("redshift_native_auth enabled")
    331 if not redshift_native_auth:
--> 332     IamHelper.set_iam_properties(info)
    334 _logger.debug(make_divider_block())
    335 _logger.debug("Connection arguments following validation and IAM auth (if applicable)")

File ~/Library/Python/3.9/lib/python/site-packages/redshift_connector/iam_helper.py:116, in IamHelper.set_iam_properties(info)
    112     if info.cluster_identifier is None and not info._is_serverless:
    113         raise InterfaceError(
    114             "Invalid connection property setting. cluster_identifier must be provided when IAM is enabled"
    115         )
--> 116     IamHelper.set_iam_credentials(info)
    117 # Check for Browser based OAuth Native authentication
    118 NativeAuthPluginHelper.set_native_auth_plugin_properties(info)

File ~/Library/Python/3.9/lib/python/site-packages/redshift_connector/iam_helper.py:176, in IamHelper.set_iam_credentials(info)
    173                 info.db_groups = db_groups
    175 if not isinstance(provider, INativePlugin):
--> 176     IamHelper.set_cluster_credentials(provider, info)

File ~/Library/Python/3.9/lib/python/site-packages/redshift_connector/iam_helper.py:360, in IamHelper.set_cluster_credentials(cred_provider, info)
    358 except botocore.exceptions.ClientError as e:
    359     _logger.error("ClientError: %s", e)
--> 360     raise e
    361 except Exception as e:
    362     _logger.error("other Exception: %s", e)

File ~/Library/Python/3.9/lib/python/site-packages/redshift_connector/iam_helper.py:335, in IamHelper.set_cluster_credentials(cred_provider, info)
    324     cred = typing.cast(
    325         typing.Dict[str, typing.Union[str, datetime.datetime]],
    326         client.get_cluster_credentials_with_iam(
   (...)
    330         ),
    331     )
    332 else:
    333     cred = typing.cast(
    334         typing.Dict[str, typing.Union[str, datetime.datetime]],
--> 335         client.get_cluster_credentials(
    336             DbUser=info.db_user,
    337             DbName=info.db_name,
    338             DbGroups=info.db_groups,
    339             ClusterIdentifier=info.cluster_identifier,
    340             AutoCreate=info.auto_create,
    341         ),
    342     )
    344 if info.iam_disable_cache is False:
    345     IamHelper.credentials_cache[cache_key] = typing.cast(
    346         typing.Dict[str, typing.Union[str, datetime.datetime]], cred
    347     )

File ~/Library/Python/3.9/lib/python/site-packages/botocore/client.py:530, in ClientCreator._create_api_method.<locals>._api_call(self, *args, **kwargs)
    526     raise TypeError(
    527         f"{py_operation_name}() only accepts keyword arguments."
    528     )
    529 # The "self" in this scope is referring to the BaseClient.
--> 530 return self._make_api_call(operation_name, kwargs)

File ~/Library/Python/3.9/lib/python/site-packages/botocore/client.py:960, in BaseClient._make_api_call(self, operation_name, api_params)
    958     error_code = parsed_response.get("Error", {}).get("Code")
    959     error_class = self.exceptions.from_code(error_code)
--> 960     raise error_class(parsed_response, operation_name)
    961 else:
    962     return parsed_response

ClientError: An error occurred (AccessDenied) when calling the GetClusterCredentials operation: User: arn:aws:sts::{account_number}:assumed-role/Redshift/{username} is not authorized to perform: redshift:JoinGroup on resource: arn:aws:redshift:us-east-1:{account_no}:dbgroup:{cluster_id}/{group_name1},{group_name2} because no identity-based policy allows the redshift:JoinGroup action

## Reproduction code
import redshift_connector
 
# Connects to Redshift cluster using Okta MFA Browser Plugin
conn = redshift_connector.connect(
    iam=True,
    host={HOST NAME},
    port=5439,
    database={DB_NAME}',
    db_user='{username}',
    cluster_identifier={cluster_id},
    region='us-east-1',
    login_url='{okt login url}',
    credentials_provider='BrowserSamlCredentialsProvider',
    password='',
    db_groups=['group_name']
)

**Comment by Brooke-white** [comment]
Hi @selvathiruarul ,

Thanks for reaching out regarding this issue. While I'm not familiar on the specifics of your setup, my guess would be that this failure is due to the configuration of the organization identity policy. redshift-connector's internal CI runs connection tests for a variety of identity providers, including Okta, and confirms successful connection with/without `db_groups`. But of course this is based on how we have setup the identity providers, such as Okta, for our CI. 

While `db_groups` parameter is not required for Okta MFA, it looks to be required based on your organizations configuration. My recommendation would be to include the `db_groups` parameter to ensure successful connection.

**Comment by selvathiruarul** [comment]
Hi, @Brooke-white  db_groups are not required in any other clients like a workbench or data grid.  It only fails in the redshift connector. We also confirmed with AWS support that our configuration is good.  It seems like a redshift-connector requirement.

**Comment by Brooke-white** [comment]
Which driver and version is in use with workbench where issue isn't seen? @selvathiruarul

**Comment by selvathiruarul** [comment]
redshift-jdbc42-2.1.0.11 
https://docs.aws.amazon.com/redshift/latest/mgmt/jdbc20-download-driver.html. It also works with ODBC without db_groups.

**Comment by Brooke-white** [comment]
Interesting, thank you for sharing this. I will investigate to see what difference exists in the redshift-connector logic for this section of the codebase and update with my findings.

**Comment by Brooke-white** [comment]
And just to confirm, you're seeing this difference in behavior when authenticating with the same Redshift cluster and Okta setup? @selvathiruarul

**Comment by selvathiruarul** [comment]
Yes, that's right @Brooke-white. It's happening on the same cluster. We are able to connect to the cluster without db groups from client tools like a workbench, excel odbc, and data grip but not redshift-connector.

**Comment by selvathiruarul** [comment]
@Brooke-white  We found the issue, it's because of the way OKTA accepts multiple groups. This is an okta issue. I'll close this ticket for now.  
https://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Amazon-Web-Services-Redshift.html#:~:text=Allowed%20DB%20Groups,Save%20/%20Next%3A
This is changed in the new version and it doesn't accept the groups properly. 

Thank you.
