### ISSUE TITLE
python 3.11 support?

### ISSUE THREAD

**Issue by tooptoop4** [aws/amazon-redshift-python-driver#154]
## Problem description

1. Expected behaviour:
2. Actual behaviour:
3. Error message/stack trace:
4. Any other details that can be helpful:

**Comment by Brooke-white** [comment]
Hi @tooptoop4 , Python 3.11 is supported. We just need to update our docs to indicate this. I'll keep this issue open until we make this adjustment.

**Comment by Brooke-white** [comment]
I've updated our docs to indicate support. thank you again for raising this issue!
