### ISSUE TITLE
Wrong Avg result when running query

### ISSUE THREAD

**Issue by ni-todo-spot** [aws/amazon-redshift-python-driver#159]
## Driver version
2.0.910

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.50300\x00\x00

## Client Operating System
Darwin Foo-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

## Python version
3.8.13

## Problem description
ran the following query:

```sql
SELECT (AVG(("base_query"."FOO")::float8)) AS "AVG_RES" FROM (SELECT (0.5) AS "FOO" FROM (SELECT 1) "test_168431975518178" UNION ALL SELECT (1.5) AS "FOO" FROM (SELECT 1) "test_168431975518219") "base_query"
```

expected to get 1 as result, got 0.

**Comment by Brooke-white** [comment]
Hi @ni-todo-spot, if you have Redshift console, JDBC/ODBC driver or psql CLI accessible do you see this issue when using those clients as well?

Using the provided query and a Redshift cluster with version [1.0.50300](https://docs.aws.amazon.com/redshift/latest/mgmt/cluster-versions.html), I attempted to reproduce but was unable to do so via redshift-connector or Redshift JDBC driver. Both client tools returned `1.4916681462400413e-154`.

**Comment by ni-todo-spot** [comment]
> Hi @ni-todo-spot, if you have Redshift console, JDBC/ODBC driver or psql CLI accessible do you see this issue when using those clients as well?
> 
> Using the provided query and a Redshift cluster with version [1.0.50300](https://docs.aws.amazon.com/redshift/latest/mgmt/cluster-versions.html), I attempted to reproduce but was unable to do so via redshift-connector or Redshift JDBC driver. Both client tools returned `1.4916681462400413e-154`.

Thanks for your reply!
Actually, I was not 100% accurate with you regarding redshift's output.
The actual output was as you mentioned `1.4916681462400413e-154` and not as I simply made it plain `0`.

I tried and reproduced the result, using psql CLI:

```
my_db=> SELECT (AVG(("base_query"."FOO")::float8)) AS "AVG_RES" FROM (SELECT (0.5) AS "FOO" FROM (SELECT 1) "test_168431975518178" UNION ALL SELECT (1.5) AS "FOO" FROM (SELECT 1) "test_168431975518219") "base_query" ;
        avg_res        
-----------------------
 1.49166814624004e-154
(1 row)
```

Sorry if I mislead you and wI highly appreciate you trying to help out :)

If I can assist you with any other information I'll be glad to that.


Thanks!

**Comment by Brooke-white** [comment]
Hey @ni-todo-spot , thanks for sharing this information! To clarify, you expecting `1` but getting `1.49166814624004e-154` instead? 

If this is the case, I'd recommend to open a ticket with AWS Support. As all three clients (PSQL, redshift-connector, and Redshift JDBC 2.x) are returning the same result, my inclination is that investigation of this behavior on the Redshift server-side is needed. Please reference this GitHub issue if you reach out to AWS support.

**Comment by ni-todo-spot** [comment]
@Brooke-white Yes I was expecting 1.

Thank you for your help!

**Comment by Brooke-white** [comment]
no problem, I'll be closing this issue for now but feel free to re-open if needed.
