### ISSUE TITLE
2.0.912 results in OSError on attempt to connect with database

### ISSUE THREAD

**Issue by austinweisgrau** [aws/amazon-redshift-python-driver#172]
## Driver version
2.0.912

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.51973

## Client Operating System
Ubuntu 22.04

## Python version
Python 3.10.12

## Problem description

I wanted to submit this bug as soon as I isolated it to this package - I'll need to loop back with a full isolation.

Currently I know that dbt-redshift==1.5.2 cannot connect to Redshift using 2.0.912. It results in a `OSError('Int or String expected'))`. The error is emitted by [this line](https://github.com/aws/amazon-redshift-python-driver/blob/b2dde82ec9156e2adcc801ac54c051f3cfe61e33/redshift_connector/core.py#L610). Downgrading to 2.0.911 fixes the error.

I will return to this to further isolate the behavior and produce a minimal reproducible example once I triage impacts.

1. Expected behaviour: 
2. Actual behaviour:
3. Error message/stack trace: 
4. Any other details that can be helpful:

**Comment by Brooke-white** [comment]
Hi @austinweisgrau, thanks for reaching out. this is a known issue and is being tracked in https://github.com/dbt-labs/dbt-redshift/issues/518. Until this issue is resolved, the dbt team's recommendation is downgrading to redshift-connector==2.0.211, as you've mentioned above.
