### ISSUE TITLE
remove postgres-only code

### ISSUE THREAD

**Issue by dataders** [aws/amazon-redshift-python-driver#173]
when querying `pg_views`, redshift coerces materialized views to be of `relkind='v'`, so the below case statement is not relevant to Redshift at all. I wish that Redshift wouldn't do this, but I'll take as a consolation prize that the redshift python connector not have coded references to `relkind='m'`

https://github.com/aws/amazon-redshift-python-driver/blob/b2dde82ec9156e2adcc801ac54c051f3cfe61e33/redshift_connector/cursor.py#L927

**Comment by Brooke-white** [comment]
Hi @dataders , thank you for taking the time to open this issue as well as the associated pull request. Given we align these metadata queries across all of our Redshift drivers, we will need to discuss this with the Redshift team before making any changes.

If you can please provide the following information to aid our team's discussion of this issue:

- What impact is seen by this case statement's presence?
- Which version of Redshift server was in use when this was discovered?

I'll post updates here as they become available.

**Comment by Brooke-white** [comment]
Closing this issue out as we plan to address it in internally
