### ISSUE TITLE
Missing connection autocommit documentation

### ISSUE THREAD

**Issue by GergelyKalmar** [aws/amazon-redshift-python-driver#20]
It is unclear at the moment whether autocommit can be turned on on a given connection. From https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/core.py#L417 it seems that it should be possible by setting `connection.autocommit = True`, but it is unclear if this would work as expected. It would be great to document this.

**Comment by Brooke-white** [comment]
Hey @GergelyKalmar ,

Thanks for reporting this issue -- we will add some documentation regarding auto commit in our next release. By default `connection.autocommit` is set to `False` per PEP-249 [ref](https://www.python.org/dev/peps/pep-0249/#commit)

**Comment by GergelyKalmar** [comment]
It might be a good idea to expose this option through an argument for `Connection.__init__` too. Would manual rollbacks still be needed on DatabaseErrors with autocommit?

**Comment by Brooke-white** [comment]
Thank you for the feedback regarding providing adding `autocommit` as an argument to `Connection.__init__` -- I will share this with the team and keep you updated. 

> Would manual rollbacks still be needed on DatabaseErrors with autocommit?
That is correct, `rollback()` must be called manually

**Comment by GergelyKalmar** [comment]
Awesome, thank you very much for the help!

**Comment by Brooke-white** [comment]
Documentation for `autocommit` has been added as of [v2.0.875](https://github.com/aws/amazon-redshift-python-driver/blob/master/CHANGELOG.md#v20875-2021-03-08)
