### ISSUE TITLE
Redshift_connector import error in AWS Lambda

### ISSUE THREAD

**Issue by cosminpurcaru** [aws/amazon-redshift-python-driver#200]
## Driver version
N/A

## Redshift version
N/A

## Client Operating System
Linux

## Python version
python 3.9

## Table schema
N/A

## Problem description
While deploying code to AWS Lambda that imports redshift_connector module, I get this poor/deficient error:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'trackerview': scramp
Traceback (most recent call last):
```

I tried getting more information from the stack trace by cathing any error right at the import step, and these were the results:

```
import redshift_connector
File "/opt/python/redshift_connector/__init__.py", line 10, in <module>
from redshift_connector.core import BINARY, Connection, Cursor
File "/opt/python/redshift_connector/core.py", line 18, in <module>
from scramp import ScramClient  # type: ignore
File "/opt/python/scramp/__init__.py", line 15, in <module>
__version__ = version("scramp")
File "/var/lang/lib/python3.9/importlib/metadata.py", line 569, in version
return distribution(distribution_name).version
File "/var/lang/lib/python3.9/importlib/metadata.py", line 542, in distribution
return Distribution.from_name(distribution_name)
File "/var/lang/lib/python3.9/importlib/metadata.py", line 196, in from_name
raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: scramp
[ERROR] Runtime.ImportModuleError: Unable to import module 'main': Error while importing redshift_connector module in sql.py
Traceback (most recent call last):
```
I checked the python environment of the lambda and the `scramp` module is present (version `1.4.4`)

The `redshift_connector` version I am using is `2.0.917`

## Python Driver trace logs
N/A

## Reproduction code
`import redshift_connector` in AWS Lambda

**Comment by cosminpurcaru** [comment]
We're using an internal plugin for packaging dependencies and this may be a possible cause...so still investigating on our end.

**Comment by Meera-W** [comment]
Was a solution for this error found?

**Comment by learncode1146** [comment]
I am also running into the same issue when trying to use this library in aws glue shell environment. 
Can someone please share some insights on why we are getting this error even though the scramp module is present. 

importlib.metadata.PackageNotFoundError: scramp

During handling of the above exception, another exception occurred:

**Comment by James-Lingmeng-Li** [comment]
Was there a solution for this problem?

**Comment by vchow-allcloud** [comment]
@cosminpurcaru Also interested in seeing if there is a solution to this problem
