### ISSUE TITLE
Python AWS

### ISSUE THREAD

**Issue by djyos1** [aws/amazon-redshift-python-driver#211]

**Comment by Brooke-white** [comment]
Hi @djyos1 , what can we help you with?

**Comment by Vicks2thori** [comment]
Can you explain to me how I can create AWS-style Python projects? @Brooke-white

**Comment by Brooke-white** [comment]
If you're using redshift, you can review our [README](https://github.com/aws/amazon-redshift-python-driver/blob/master/README.rst) which provides a number of tutorials. If your question is more focused to generic AWS services I'd recommend to review AWS developer documentation and blogs.
