### ISSUE TITLE
Support reading .sql files

### ISSUE THREAD

**Issue by bones2peaches** [aws/amazon-redshift-python-driver#222]
Hello,

I have been working on a function that enables the execution of .sql files using the AWS Redshift Connector class. Before proceeding with a pull request, I wanted to discuss this idea and ensure it aligns with the project's goals.

Function Overview:

- The function reads and executes .sql files within the Redshift environment using the existing Connector class.
- It aims to streamline SQL script execution, making it more efficient and user-friendly.

I have reviewed the contribution guidelines and existing issues, and I believe this feature could be a valuable addition. I am eager to contribute and would appreciate any feedback or suggestions on this proposal.

Is this something that would be worthwhile to work on? If so, I will proceed with the development and submit a pull request.

Thank you for your time and consideration!

**Comment by Brooke-white** [comment]
Hi @bones2peaches , thank you for reaching out and sharing this idea with us. We've had a number of requests for this functionality over the years, but the team has opted to not include this functionality within redshift-connector, instead recommending the use of tools such as file reader + sqlparse to break up a sql file into individually executable statements which can then be passed to redshift-connector. 

With that said, the team appreciates your interest in contributing and the time you've spent towards this functionality.
