### ISSUE TITLE
Allow inline type hints to be packaged and distributed (PEP561)

### ISSUE THREAD

**Issue by jamesdow21** [aws/amazon-redshift-python-driver#223]
## Problem description

It looks like this package has type annotations fully specified inline, but mypy doesn't recognize that the type hints can be used without a "py.typed" marker file (as described in [PEP561](https://peps.python.org/pep-0561/)).  

1. Expected behaviour: Mypy recognizes the inline annotations
2. Actual behaviour: Mypy errors and skips analyzing anything from the package
3. Error message/stack trace: `error: Skipping analyzing "redshift_connector": module is installed, but missing library stubs or py.typed marker  [import-untyped]`
4. Any other details that can be helpful: Very simple fix, just need to add a blank file named "py.typed" to the package root and make sure setuptools includes it in the sdist and wheel

**Comment by Brooke-white** [comment]
Hi @jamesdow21 , my apologies for the delay in response for this issue and your PR. Also, thank you for taking the time to open a PR for this issue.

**Comment by DavidGeorge528** [comment]
Not sure if this issue is fixed. I have the latest version of redshift-connector 
`redshift-connector==2.1.3`

And inside my site-packages I don't see the `py.typed` file

![image](https://github.com/user-attachments/assets/50e0d14d-800f-493c-87b0-7251b112a196)

And I also still get the error from mypy:

```python
redshift.py:1:1: error: Skipping analyzing "redshift_connector": module is installed, but missing library stubs or py.typed marker  [import-untyped]
redshift.py:1:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

**Comment by jamesdow21** [comment]
@Brooke-white Do you have any insight on what might be different between the local build script and the actual build and publish steps that upload the wheel to PyPI?
