### ISSUE TITLE
Make cursor paramstyle configurable

### ISSUE THREAD

**Issue by GergelyKalmar** [aws/amazon-redshift-python-driver#23]
Currently `connection.cursor()` does not seem to allow specifying the paramstyle for the returned cursor – it would be great if this functionality could be exposed. I assume that setting `cursor.paramstyle` to the desired value should work as expected, but this does not seem to be documented at the moment.

**Comment by Brooke-white** [comment]
Hey @GergelyKalmar ,

The team is currently in the process of improving documentation for `redshift_connector`, I'll forward along your feedback so we can improve transparency of `paramstyle`.

In the meantime, I've quickly jotted down some high-level examples of each of the `paramstyle` types.

- Valid values for `paramstyle` are `qmark`, `numeric`, `named`, `format`, and `pyformat`
- The default value of `paramstyle` is `format`
- Setting `cursor.paramstyle` to one of the valid values mentioned above will allow you to use it as expected. 


Examples of each `paramstyle`
```python
# qmark
redshift_connector.paramstyle = 'qmark'
sql = 'insert into foo(bar, jar) VALUES(?, ?)'
cursor.execute(sql, (1, "hello world"))

# numeric
redshift_connector.paramstyle = 'numeric'
sql = 'insert into foo(bar, jar) VALUES(:1, :2)'
cursor.execute(sql, (1, "hello world"))

# named
redshift_connector.paramstyle = 'numeric'
sql = 'insert into foo(bar, jar) VALUES(:p1, :p2)'
cursor.execute(sql, p1=1, p2="hello world")

# format
redshift_connector.paramstyle = 'format'
sql = 'insert into foo(bar, jar) VALUES(%s, %s)'
cursor.execute(sql, (1, "hello world"))

# pyformat
redshift_connector.paramstyle = 'pyformat'
sql = 'insert into foo(bar, jar) VALUES(%(bar)s, %(jar)s)'
cursor.execute(sql, {"bar": 1, "jar": "hello world"})
```

**Comment by GergelyKalmar** [comment]
Wonderful, thank you very much!
