### ISSUE TITLE
Asyncio Support

### ISSUE THREAD

**Issue by bmoscon** [aws/amazon-redshift-python-driver#26]
This is more a feature request/question. Are there any plans to support asyncio in this project? I dont see anything in the code, docs, or open/closed tickets about this, so maybe I'm the first to ask?

**Comment by Brooke-white** [comment]
Hey @bmoscon ,

Thanks for reaching out. Could you share a bit about your use case and how asyncio support would be beneficial to your project? We have not had any customer requests for this functionality so far, but the Redshift drivers team will discuss your request and let you know.

**Comment by bmoscon** [comment]
my application uses asyncio and I want to write data to redshift. If i do not use an asyncio enabled driver, it will block the event loop while the write is pending. Since I anticipate a lot of writes, this can be a large bottleneck on the performance of the application. I'm not sure how familiar you are with asyncio, but typically once you decide to make use of aio you need to use async libraries for all the I/O heavy parts of the code or you lose any benefits you might gain from using asyncio.

**Comment by Brooke-white** [comment]
Thanks @bmoscon !

Could you describe the driver functionalities that would need to support the asyncio framework for your use case? I'm not very familiar with asyncio, but assume operations like `execute()`, `fetch()`, `connect()`, and maybe more, would need to support aio. 

Also, could you provide a code snippet of how you imagine using an asyncio enabled redshift_connector.

**Comment by bmoscon** [comment]
`connect` is probably less important, but it would be useful if connect supported asyncio. Definitely methods/functions that interact with the database (for reading or writing data) will need to support aio to get any benefit out of it. 


Some pseudocode would be something like this:


```python
conn = await aws_redshift.connect(....)

async with conn.cursor() as c:
     await c.execute("INSERT ..... INTO ..... VALUES .....")

```

**Comment by Brooke-white** [comment]
Hi @bmoscon ,

Thank you for your patience. After discussing this feature internally, the team has determined it does not fall on our roadmap for the immediate future.

**Comment by zwing99** [comment]
@Brooke-white et al, I think you should reconsider your prioritization of this feature. Modern python frameworks (fastapi for example) are considering ayncio as a first class citizen. Please consider re-opening and evaluating this again.

**Comment by Nikohm** [comment]
will this make it onto the feature roadmap for `redshift_connector`?
