### ISSUE TITLE
Is it possible hidden the password or other credential from Connection Object ?

### ISSUE THREAD

**Issue by jackmokcx** [aws/amazon-redshift-python-driver#28]
## Problem description

1. Expected behaviour:
2. Actual behaviour:
3. Error message/stack trace:
4. Any other details that can be helpful:

**Comment by Brooke-white** [comment]
Hey @jackmokcx ,

Thanks for reaching out. Using an Identity Provider (IdP) plugin can allow you to access an Amazon Redshift cluster without directly providing AWS credentials and password. The following IdPs are supported:
- Active Directory Federation Services via `AdfsCredentialsProvider`
- Okta via `OktaCredentialsProvider`
- PingFederate via `PingCredentialsProvider`
- Microsoft Azure Active Directory via `AzureCredentialsProvider`
- SAML MFA via `BrowserSamlCredentialsProvider`
- Microsoft Azure Active Directory SSO via `BrowserAzureCredentialsProvider`

Additional IdPs may be supported by using the generic `SamlCredentialsProvider` or `BrowserSamlCredentialProvider` IdP Plugin. 

When using an IdP Browser plugin or anticipating a SAML response containing a password or other credential information, the relevent parameters to the `connect(...)` method should be set to an empty string. 

Here is an example of authentication using `Okta` IdP. Please note the `user` and `password` parameters provided are for authenticating via the IdP, Okta, and are not the `user` and `password` for the Amazon Redshift cluster.

```python
    import redshift_connector

    con: redshift_connector.Connection = redshift_connector.connect(
        iam=True,
        database='dev',
        host='my-testing-cluster.abc.us-east-2.redshift.amazonaws.com',
        cluster_identifier='my-testing-cluster',
        credentials_provider='OktaCredentialsProvider',
        user='brooke@myazure.org',
        password='hunter2',
        idp_host='my_idp_host',
        app_id='my_first_appetizer',
        app_name='dinner_party'
    )
```

Below I've included an example of authenticating using IAM credentials and the AWS `default` profile. Using this approach would allow the user to provide temporary AWS credentials to the Connection object, which are stored in `~/.aws/credentials`. Please see this article on [Identity and access management in Amazon Redshift](https://docs.aws.amazon.com/redshift/latest/mgmt/redshift-iam-authentication-access-control.html) for more information about configuraiton.

```python
    import redshift_connector

    # Connects to Redshift cluster using IAM credentials from default profile defined in ~/.aws/credentials
    conn: redshift_connector.Connection = redshift_connector.connect(
        iam=True,
        database='dev',
        db_user='awsuser',
        password='',
        user='',
        cluster_identifier='examplecluster',
        profile='default'
     )
```
