### ISSUE TITLE
Update scramp dependency constraints to allow usage of version 1.4.0

### ISSUE THREAD

**Issue by jaklan** [aws/amazon-redshift-python-driver#34]
Related issue:
https://github.com/awslabs/aws-data-wrangler/issues/704

Changelog for `scramp`:
>Version 1.4.0, 2021-03-28
Raise an exception if the client receives an error from the server.

**Comment by Brooke-white** [comment]
Hi @jaklan, thank you for reaching out about this issue. The team is working on a fix for this issue and plans to make a release this coming Monday, May 24th.

**Comment by Brooke-white** [comment]
Hi @jaklan , release [2.0.811](https://github.com/aws/amazon-redshift-python-driver/blob/v2.0.881/CHANGELOG.md#v20881-2021-05-19) has been made. This release updates the scramp dependency. Please reach out if you continue to experience issues with redshift_connector and pipenv

**Comment by jaklan** [comment]
Great to hear! Thanks for the quick reaction 😉
