### ISSUE TITLE
Redshift Driver Requires user and password for Adfs Authentication when user and password are null

### ISSUE THREAD

**Issue by jacwillis** [aws/amazon-redshift-python-driver#38]
## Driver version
2.0.0.0.4

## Client Operating System
Windows

## Python version
Python 3.8.3

## Problem description
I'm trying to connect to a redshift database using Adfs Authentication without a username or password. However, when I insert user='',password='' the system rejects it. I saw there was a commit ~10 days ago trying to fix this issue, but it appears to fail within the iam_helper.py module, which seems to require these parameters. Any help would be lovely!

3. Error message/stack trace:
TypeError                                 Traceback (most recent call last)
C:\Anaconda3\lib\site-packages\redshift_connector\plugin\saml_credentials_provider.py in get_credentials(self)
     59             try:
---> 60                 self.refresh()
     61             except Exception as e:

C:\Anaconda3\lib\site-packages\redshift_connector\plugin\saml_credentials_provider.py in refresh(self)
     86         # decode SAML assertion into xml format
---> 87         doc: bytes = base64.b64decode(saml_assertion)
     88         soup = bs4.BeautifulSoup(doc, "xml")

C:\Anaconda3\lib\base64.py in b64decode(s, altchars, validate)
     79     """
---> 80     s = _bytes_from_decode_data(s)
     81     if altchars is not None:

C:\Anaconda3\lib\base64.py in _bytes_from_decode_data(s)
     44     except TypeError:
---> 45         raise TypeError("argument should be a bytes-like object or ASCII "
     46                         "string, not %r" % s.__class__.__name__) from None

TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

During handling of the above exception, another exception occurred:

InterfaceError                            Traceback (most recent call last)
<ipython-input-17-6e8885ddc8db> in <module>
     13 
     14 
---> 15 conn = redshift_connector.connect(
     16     iam=True,
     17     host='',

C:\Anaconda3\lib\site-packages\redshift_connector\__init__.py in connect(user, database, password, port, host, source_address, unix_sock, ssl, sslmode, timeout, max_prepared_statements, tcp_keepalive, application_name, replication, idp_host, db_user, app_id, app_name, preferred_role, principal_arn, access_key_id, secret_access_key, session_token, profile, credentials_provider, region, cluster_identifier, iam, client_id, idp_tenant, client_secret, partner_sp_id, idp_response_timeout, listen_port, login_url, auto_create, db_groups, force_lowercase, allow_db_user_override, client_protocol_version, database_metadata_current_db_only, ssl_insecure, web_identity_token, role_session_name, role_arn)
    248     """
    249     info: RedshiftProperty = RedshiftProperty()
--> 250     IamHelper.set_iam_properties(
    251         info,
    252         user=user,

C:\Anaconda3\lib\site-packages\redshift_connector\iam_helper.py in set_iam_properties(info, user, host, database, port, password, source_address, unix_sock, ssl, sslmode, timeout, max_prepared_statements, tcp_keepalive, application_name, replication, idp_host, db_user, iam, app_id, app_name, preferred_role, principal_arn, access_key_id, secret_access_key, session_token, profile, credentials_provider, region, cluster_identifier, client_id, idp_tenant, client_secret, partner_sp_id, idp_response_timeout, listen_port, login_url, auto_create, db_groups, force_lowercase, allow_db_user_override, client_protocol_version, database_metadata_current_db_only, ssl_insecure, web_identity_token, role_session_name, role_arn)
    258 
    259         if info.iam is True:
--> 260             IamHelper.set_iam_credentials(info)
    261         else:
    262             return

C:\Anaconda3\lib\site-packages\redshift_connector\iam_helper.py in set_iam_credentials(info)
    295 
    296         if isinstance(provider, SamlCredentialsProvider):
--> 297             credentials: CredentialsHolder = provider.get_credentials()
    298             metadata: CredentialsHolder.IamMetadata = credentials.get_metadata()
    299             if metadata is not None:

C:\Anaconda3\lib\site-packages\redshift_connector\plugin\saml_credentials_provider.py in get_credentials(self)
     61             except Exception as e:
     62                 _logger.error("refresh failed: {}".format(str(e)))
---> 63                 raise InterfaceError(e)
     64         # if the SAML response has db_user argument, it will be picked up at this point.
     65         credentials: CredentialsHolder = self.cache[key]

InterfaceError: argument should be a bytes-like object or ASCII string, not 'NoneType'
4. Any other details that can be helpful:
This is happening within a gov-cloud enviornment if that makes any difference.

## Reproduction code
conn = redshift_connector.connect(
    iam=True,
    host='',
    port=5439,
    database='',
    cluster_identifier='',
    region='',
    idp_host = '',
    idp_response_timeout = '30',
    #listen_port = '443',
    credentials_provider='AdfsCredentialsProvider',
    user='',
    password=''
)

**Comment by Brooke-white** [comment]
Hey @jacwillis ,

Thanks for reaching out regarding this issue and digging into the code. Could you clarify what you mean by
> I'm trying to connect to a redshift database using Adfs Authentication without a username or password.

When working with the ADFSCredentialsProvider, the `user` and `password` parameters to the `connect(...)` method are usually populated with the `user` and `password` values for authenticating with the ADFS server that has been set up. For example:

```python
conn = redshift_connector.connect(
  iam=True,
  host='',
  port=5439,
  database='dev',
  cluster_identifier=''myCluster,
  region='us-west-2',
  idp_host = 'ec2-xx-xxx-xx-xxx.us-west-2.computer.amazonaws.com',
  idp_response_timeout = '30',
  #listen_port = '443',
  credentials_provider='AdfsCredentialsProvider',
  user='brooke@ec2-xx-xxx-xx-xxx.us-west-2.computer.amazonaws.com',
  password='myADFSPassword'
)
```

**Comment by Brooke-white** [comment]
closing this issue for now, please feel free to re-open if you're still experiencing any issue
