### ISSUE TITLE
Can I insert param special string data as a value?

### ISSUE THREAD

**Issue by da-huin** [aws/amazon-redshift-python-driver#41]
## Driver version
2.0.882

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.27747

## Client Operating System
Amazon Linux 

## Python version
Python 3.6.8

## Table schema

mid BIGINT NOT NULL,
message varchar(65535) NOT NULL

## Problem description

It works fine.
`
cursor.executemany('INSERT INTO sample (mid,message) values (%s,%s)', [(123, 'hello')])
`

It goes into the pending state without any message.
`
cursor.executemany('INSERT INTO sample (mid,message) values (%s,%s)', [(123, ':hello')])
`

**Comment by Brooke-white** [comment]
Hi @da-huin ,

I ran the two following code snippits using Python. 3.9 but was unable to reproduce. If the code snippit  does not match your setup please let me know and I will adjust it.

```python
import redshift_connector

with redshift_connector.connect(
    host='XXXX.redshift.amazonaws.com',
    user='XXXX',
    password='XXXX',
    database='XXXX'
) as conn:
    with conn.cursor() as cursor:
        cursor.execute('drop table if exists sample')
        cursor.execute('CREATE TABLE sample(mid BIGINT NOT NULL, message VARCHAR(65535) NOT NULL)')
        cursor.executemany('INSERT INTO sample (mid,message) values (%s,%s)', [(123, ':hello')])
        cursor.execute("SELECT * FROM sample")
        print(cursor.fetchall())
```

```bash
➜  scratches python3 issue_41.py 
([123, ':hello'],)
➜  scratches python3 --version
Python 3.6.8
```

In your script are there any long running transactions being executed? There is an open issue, #33 , where long running transactions can cause behavior like this to occur.

**Comment by da-huin** [comment]
```python
import redshift_connector

conn = redshift_connector.connect(
    host='XXXX.redshift.amazonaws.com',
    user='XXXX',
    password='XXXX',
    database='XXXX'
)
cursor: redshift_connector.Cursor = conn.cursor()
table_name = 'sample'

cursor.executemany('INSERT INTO sample (mid,message) values (%s,%s)', [(123, 'hello')])
# cursor.executemany('INSERT INTO sample (mid,message) values (%s,%s)', [(123, ':hello')])
```

I ran it in a jupyter notebook, ran it once with a `hello`, changed it to a `:hello` and ran it again. So I mistook it for a param special string problem. 
It works well when used with the `with` reserved word. Thank you!
