### ISSUE TITLE
multiline sql with transacr 

### ISSUE THREAD

**Issue by dburtsev** [aws/amazon-redshift-python-driver#46]
## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.28422
## Client Operating System
Windows 10

## Python version
3.7 64bit
## Table schema
CREATE TABLE dev.test4(id INT IDENTITY, strng TEXT );

## Problem description

1. Expected behaviour:
return new identity from table
2. Actual behaviour: error
3. Error message/stack trace:
4. Any other details that can be helpful:

## Python Driver trace logs
Traceback (most recent call last):
  File "C:\Work\Python\AuditLog.py", line 52, in <module>
    cursor.execute(sql)
  File "C:\Users\Dmitriy.Burtsev\AppData\Local\Programs\Python\Python37\lib\site-packages\redshift_connector\cursor.py", line 211, in execute
    self._c.execute(self, operation, args)
  File "C:\Users\Dmitriy.Burtsev\AppData\Local\Programs\Python\Python37\lib\site-packages\redshift_connector\core.py", line 1192, in execute
    self.handle_messages(cursor)
  File "C:\Users\Dmitriy.Burtsev\AppData\Local\Programs\Python\Python37\lib\site-packages\redshift_connector\core.py", line 1351, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'cannot insert multiple commands into a prepared statement', 'F': '/home/ec2-user/padb/src/pg/src/backend/tcop/postgres.c', 'L': '2801', 'R': 'exec_parse_message'}

## Reproduction code
import redshift_connector
conn = redshift_connector.connect(
    host='qwe.us-east-1.redshift.amazonaws.com',
    database='qwe',
    user='qwe',
    password='qwe',
    port = 5439,
    ssl = False
 )
cursor: redshift_connector.Cursor = conn.cursor()
sql = """BEGIN TRANSACTION;
INSERT INTO dev.test4 (strng) VALUES ('XYZ');
SELECT MAX(id) AS newid FROM dev.test4 WHERE strng = 'XYZ'
COMMIT TRANSACTION;"""
cursor.execute(sql)
conn.close

**Comment by Brooke-white** [comment]
Hi @dburtsev ,

redshift_connector uses prepared statements when executing statements. This means that multi-statements are not supported at this time. At this time we recommend you split up the SQL statements prior to passing them to the `cursor.execute(...)` method.

**Comment by dburtsev** [comment]
Will do

**Comment by easthy-alterpost** [comment]
I have to run multiple statements due to query perfomance improvements. For example:

```
BEGIN TRANSACTION;

DROP TABLE IF EXISTS _tmp
;
CREATE TEMPORARY TABLE _tmp (
key char(32) DISTKEY,
....
)
DISTSTYLE KEY
SORTKEY(key)
;
INSERT INTO _tmp
SELECT *
   FROM table_2 ....
;

INSERT INTO table_3
SELECT *
  FROM table_1
             INNER JOIN _tmp
             ON _tmp.key = table.key
WHERE....
;
END TRANSACTION;
```

I can do it with Postgres driver, but can't with redshift. This functionality should be implemented.

**Comment by Brooke-white** [comment]
Hi @easthy-alterpost  -- this functionality is not currently supported due to how redshift_connector uses prepared statements for statement execution. While adding this functionality is not currently on our roadmap, I will pass along your feedback to the Amazon Redshift driver team. 

If you're interested in why this isn't currently supported, you can checkout [my response](https://github.com/aws/amazon-redshift-python-driver/issues/39#issuecomment-915393795) in #39.
