### ISSUE TITLE
AttributeError: 'Cursor' object has no attribute 'callproc'

### ISSUE THREAD

**Issue by dburtsev** [aws/amazon-redshift-python-driver#52]
## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.29551
## Client Operating System

Windows 10
## Python version

Python 3.7.3 
## Table schema

create or replace procedure stage.sp_truncate(tables character varying)
language plpgsql as $plpgsql$

## Problem description

1. Expected behaviour:
2. Actual behaviour:
3. Error message/stack trace:
  cursor.callproc('stage.sp_truncate', tables)
AttributeError: 'Cursor' object has no attribute 'callproc'
4. Any other details that can be helpful:

**Comment by Brooke-white** [comment]
It seems the `callproc()` method is currently un-implemented. The team will work to add this functionality to the `Cursor` class. thank you for bringing this issue to our attention!

**Comment by Brooke-white** [comment]
@dburtsev -- support for `callproc()` will be included in our next release, scheduled for August 30th.

**Comment by Brooke-white** [comment]
@dburtsev , release [v2.0.886](https://github.com/aws/amazon-redshift-python-driver/releases/tag/v2.0.886) has been made and contains support for this method. Please open a new issue if you experience any issue using `callproc()`. Thanks!

**Comment by 98467** [comment]
> @dburtsev -- support for `callproc()` will be included in our next release, scheduled for August 30th.

how can i solve this problem??
