### ISSUE TITLE
AWS Lambda Redshift connections

### ISSUE THREAD

**Issue by dburtsev** [aws/amazon-redshift-python-driver#68]
We have several Glue jobs with connections to Redshift, which we want to convert to Lambda jobs.
The Glue job can reference the external library from s3. How can I do this from Lambda?
Thanks,
Dmitriy

**Comment by Brooke-white** [comment]
Hey Dmitriy,

[Deploy Python Lambda functions with .zip file archives](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html) should provide an overview of how you can do this. Specifically, [this section](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-package-with-dependency) explains how you can deploy a Lambda with redshift_connector (or any other required runtime dependencies).

Please let me know if you encounter any issue in following the above instructions and we can work to find a solution :)

**Comment by dburtsev** [comment]
Thanks @Brooke-white 
If I understand correctly, we must attach a redshift driver to each Lambda job instead of sharing the same driver from s3 as Glue job did?

**Comment by Brooke-white** [comment]
Hey @dburtsev,

> Your AWS Lambda function's code consists of scripts or compiled programs and their dependencies. You use a deployment package to deploy your function code to Lambda. 

> You can upload a .zip file as your deployment package using Amazon Simple Storage Service (Amazon S3)

ref: https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-package.html

With the setup described in the above blurbs, you'd upload a .zip file as your deployment package to S3. The .zip file, created using [the instructions from my prior post](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html), would contain your Lambda function, redshift_connector, and any other dependencies.

The .zip deployment package can be uploaded using the Lambda console. Instructions are provided in the above link.

**Comment by dburtsev** [comment]
This means no driver sharing between jobs, every Lambda job must have one redshift connector.
Thank you
