### ISSUE TITLE
Allow authentication using IAM EC2 instance profile or environment variables

### ISSUE THREAD

**Issue by rectalogic** [aws/amazon-redshift-python-driver#69]
## Driver version
2.0.900

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.33595

## Client Operating System
Ubuntu 20.04

## Python version
Python 3.8.10

## Problem description
When using IAM authentication, the driver does not seem to delegate to boto3. It doesn't pick up environment variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN`) or use the EC2 instance metadata service like boto3 normally would.
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials

What do I need to pass to `connect()` to have it delegate to boto3?

## Python Driver trace logs
```pycon
>>> conn = redshift_connector.connect(
...     iam=True,
...     database='xxx',
...     db_user='xxx',
...     cluster_identifier='myredshift',
...     region="us-west-2",
...  )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.8/site-packages/redshift_connector/__init__.py", line 327, in connect
    IamHelper.set_iam_properties(info)
  File "/tmp/venv/lib/python3.8/site-packages/redshift_connector/iam_helper.py", line 123, in set_iam_properties
    raise InterfaceError(
redshift_connector.error.InterfaceError: Invalid connection property setting. Credentials provider, AWS credentials, Redshift auth profile or AWS profile must be provided when IAM is enabled
```

**Comment by Brooke-white** [comment]
Hey @rectalogic, thanks for the heads up. 

> When using IAM authentication, the driver does not seem to delegate to boto3. It doesn't pick up environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN)

A fix will be made in our next release.

> or use the EC2 instance metadata service like boto3 normally would.

The team will work on implementing this, I'll keep this issue updated with the status.

**Comment by Brooke-white** [comment]
@rectalogic , v2.0.901 has been released. Please try using this version

**Comment by rectalogic** [comment]
Thanks, this seems to work.
