### ISSUE TITLE
[Feature request] Efficient bulk inserts (single bulk insert statement)

### ISSUE THREAD

**Issue by kishaningithub** [aws/amazon-redshift-python-driver#75]
https://github.com/aws/amazon-redshift-python-driver/blob/e0192784f5c949da50469a566599a1cc519670f1/redshift_connector/cursor.py#L235

In the above i see `executemany()` function runs the query in loop. In redshift say if i am loading thousands of records into redshift via a lambda, i would like to have a method which can run a single bulk insert statement

Eg
```sql
INSERT INTO 
    links (url, name)
VALUES
    ('https://www.google.com','Google'),
    ('https://www.yahoo.com','Yahoo'),
    ('https://www.bing.com','Bing');
```

**Comment by Yash621** [comment]
@kishaningithub can I work on this ?

**Comment by kishaningithub** [comment]
@Yash621 Sure 👍

**Comment by kishaningithub** [comment]
The `execute_values` method in psycopg2 library can probably used as an inspiration for this implementation :-) 

- https://www.psycopg.org/docs/extras.html#psycopg2.extras.execute_values
- https://billyfung.com/posts/2017-06-30-psycopg2-multiple-insert/

**Comment by iggarish** [comment]
Have you tried COPY commands? Many developers are on vacation this week. We can give you feedback next week. But at the surface, it looks good to use multi tuple insert statement.

**Comment by kishaningithub** [comment]
Thanks for the response @iggarish Yeah it is end of the year, i am fine with delayed responses :-)

From what i understand COPY is great for loading mountains of data into redshift but the use case we have is a realtime streaming one. To give more context, we are using redshift to power a realtime dashboard i.e. the data flow is like 

AWS kinesis stream -> AWS lambda -> AWS Redshift -> Dashboard

In the lambda, We receive batch of records in lambda which we want to insert using the bulk insert syntax(described above in the thread) that way we send a single SQL statement to redshift with a lot of records

Also when you say "multi tuple insert statement" which is the method in this library you are referring to? Does it send single bulk insert sql statement to redshift?

**Comment by Brooke-white** [comment]
Hi @kishaningithub,

Thank you for reaching out about your interest in this feature. I agree this would provide benefit in the mentioned use case.

@Yash621, thank you for being proactive in addressing this issue. I will take a look at your PR and provide some feedback shortly :).

**Comment by Yash621** [comment]
@Brooke-white  thank you so much :)

**Comment by Brooke-white** [comment]
@kishaningithub, please take a look at #81 so we can ensure this PR satisfies your use case :)

**Comment by Brooke-white** [comment]
Big thank you to @Yash621 for taking on this feature request and @david-dest01 for supporting this effort. PR, #81 has been merged and will be included in our next release scheduled for February.

**Comment by david-dest01** [comment]
@Yash621 nice work!

**Comment by Yash621** [comment]
@david-dest01  thank you for your support and guidance :)

**Comment by Yash621** [comment]
@Brooke-white could n't be more happy to hear that :)

**Comment by Yash621** [comment]
@Brooke-white @kishaningithub @david-dest01 it was great experience to collaborate with you all.
