### ISSUE TITLE
Error Handling (Specifically ProgrammingError handling)

### ISSUE THREAD

**Issue by mattdavis17** [aws/amazon-redshift-python-driver#80]
## Driver version

`redshift_connector==2.0.902`

## Problem description

Everything is working like expected so this is not a "this is terrible" post.  I'm trying to figure out how to handle errors when trying to execute a statement.  The statement in question is "CREATE USER ____ WITH PASSWORD ____" where I am connected to a redshift cluster.  If the user isn't there, all is great!  When the user is there, I need to handle that error.  I just can't seem to figure out error handling in that response.  I notice that there is a returned class (`<class 'redshift_connector.error.ProgrammingError'>) and this is totally fine.  I just want to know how I can handle those errors in a programmatic way.  Is there any documentation on this?

**Comment by iggarish** [comment]
You can do as below:

    try:
              with con.cursor() as cursor:
                  cursor.execute("drop table if exists t1")
          except redshift_connector.ProgrammingError:
              // ProgrammingError and handle the error

You can find more in the "test" folder. Above snippet is from test/integration/test_query.py

Hope this helps.

**Comment by Brooke-white** [comment]
Hi @mattdavis17 -- thank you for your feedback. I hope iggarish's response above addressed your question. Please let me know if any more information is needed. We will work to add documentation about this topic.

**Comment by Brooke-white** [comment]
We've added documentation to our readme regarding exceptions in  [2.0.903](https://github.com/aws/amazon-redshift-python-driver/blob/master/CHANGELOG.md#v20903-2022-01-10).
