### ISSUE TITLE
Getting timeout error when trying to establish a connection

### ISSUE THREAD

**Issue by ni-todo-spot** [aws/amazon-redshift-python-driver#84]
## Driver version
2.0.903

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.34691

## Client Operating System
Darwin Nativs-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

## Python version
3.8.7

## Problem description

1. Expected behaviour: connection established
2. Actual behaviour: timeout error
3. More info: On the free trial period
4. Error message/stack trace:

```
Traceback (most recent call last):
  File "/Users/tom/Projects/my_proj/.venv/lib/python3.8/site-packages/redshift_connector/core.py", line 544, in __init__
    self._usock.connect((host, port))
TimeoutError: [Errno 60] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/Users/tom/Projects/my_proj/.venv/lib/python3.8/site-packages/redshift_connector/__init__.py", line 336, in connect
    return Connection(
  File "/Users/tom/Projects/my_proj/.venv/lib/python3.8/site-packages/redshift_connector/core.py", line 591, in __init__
    raise InterfaceError("communication error", e)
redshift_connector.error.InterfaceError: ('communication error', TimeoutError(60, 'Operation timed out'))
```

## Reproduction code
```
import redshift_connector
conn = redshift_connector.connect(
     host='my-cluster.abc123.us-east-1.redshift.amazonaws.com',
     database='dev',
     user='awsuser',
     password='pass'
  )
```

What am I doing wrong?

**Comment by Brooke-white** [comment]
Hi @ni-todo-spot ,

As a sanity test, can you confirm if you are able to connect to Redshift using psql?

``psql -h my-cluster.abc123.us-east-1.redshift.amazonaws.com =p 5439 -U awsuser -d dev``

**Comment by ni-todo-spot** [comment]
> `psql -h my-cluster.abc123.us-east-1.redshift.amazonaws.com =p 5439 -U awsuser -d dev`

Appreciate your quick reply :)

tried all of these:

```
psql -h my-cluster.abc123.us-east-1.redshift.amazonaws.com -p 5439 -U awsuser -d dev
psql -p 5439 -U awsuser -d dev -h "my-cluster.abc123.us-east-1.redshift.amazonaws.com"
psql -d "host=my-cluster.abc123.us-east-1.redshift.amazonaws.com port=5439 dbname=dev user=awsuser"
```

which all resulted in:

```
psql: error: could not translate host name "my-cluster.abc123.us-east-1.redshift.amazonaws.com" to address: nodename nor servname provided, or not known
```


Just for reference:

```
psql --version
psql (PostgreSQL) 13.3
```

thanks in advance!

**Comment by Brooke-white** [comment]
Hey @ni-todo-spot ,

Thank you for this information. As psql is unable to connect to your cluster, I would recommend to check the following before trying to use redshift_connector, as the root issue is that your machine cannot connect to the cluster:
- (Sanity check) Are the cluster endpoint and port correct?
- Using the AWS console or CLI, is the cluster healthy and running?
- Using the AWS console or CLI, is the cluster configured for access by your IP address? If applicable, do you need to be connected to a VPN to access this cluster? Is the cluster in a VPC? Are the cluster security groups configured to accommodate your machine connecting?

Also, [Connection is refused or fails](https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-refusal-failure-issues.html) provides some references for troubleshooting this issue.

**Comment by ni-todo-spot** [comment]
Thanks for the info - I followed the instructions in the link attached to your reply and succeeded.

THANKS!
