### ISSUE TITLE
Documentation / Readme Example Clarification

### ISSUE THREAD

**Issue by nfmcclure** [aws/amazon-redshift-python-driver#89]
## Driver version
NA

## Redshift version
NA

## Client Operating System
NA

## Python version
NA

## Table schema
NA

## Problem description

1. Expected behaviour: Reference/Description to undefined variables.
2. Actual behaviour: Examples have reference to undefined variables
3. Error message/stack trace: "... is not defined"
4. Any other details that can be helpful:

The Readme has reference to functions that are not defined. The example I'm trying to work with:

```
with db_table.cursor() as cursor:
    cursor.write_dataframe(df, "book")
    cursor.execute("select * from book; ")
    result = cursor.fetchall()
```

I cannot find reference to `db_table` object. How was this created?

## Python Driver trace logs

NameError: name 'db_table' is not defined

## Reproduction code

See current readme

**Comment by Brooke-white** [comment]
Hi @nfmcclure ,

In this case, `db_table` is the Connection object created using the method `redshift_connector.connect()`. Please see the readme section [basic example](https://github.com/aws/amazon-redshift-python-driver#basic-example) to see how a connection can be established.

We will correct the naming of this variable in our docs to clarify that it is the connection object as the current naming is needlessly confusing. Thank you for taking the time to open and issue and help us improve our docs :).

**Comment by Brooke-white** [comment]
We've updated our README to address this issue in v2.0.904. Please feel free to open a new issue if you have further comments or questions.
