### ISSUE TITLE
Avoid naked exceptions

### ISSUE THREAD

**Issue by kokes** [aws/amazon-redshift-python-driver#9]
(deleted the issue template as this is not a bug per se)

The `fetch_dataframe` [features](https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/cursor.py#L282) a naked exception (`except:`), which is not the safest of patterns as very sneaky bugs can get introduced by this. I understand this exception handling is probably due to the bytes/string duality of the description, but without specifying the exact exception, one can easily get tripped by e.g. an issue in the `self.description` iteration.

(Another solution would be to do a type check and avoid the exception handling altogether.)

**Comment by Brooke-white** [comment]
Hey @kokes , 

Thank you for raising this issue. I agree the exception handling here could be improved, and doing do would make debugging much easier :). I've opened a ticket in our internal tracking system for this change and will post an update here once the change has been made. 

--brooke

**Comment by Brooke-white** [comment]
This issue has been addressed in release [v2.0.659](https://github.com/aws/amazon-redshift-python-driver/tree/v2.0.659)
