### ISSUE TITLE
Make redshift.connect a context manager

### ISSUE THREAD

**Issue by jaidisido** [aws/amazon-redshift-python-driver#92]
Transferring issue: https://github.com/awslabs/aws-data-wrangler/issues/1205

**Comment by Brooke-white** [comment]
Thanks, @jaidisido  :). @WillAyd, thank you for bringing this to our attention. The team will work to add support for this feature and provide an ETA when available.

**Comment by Brooke-white** [comment]
Hey @WillAyd, the redshift_connector `Connection` class already has an `__enter__()` and `__exit__()` method [here](https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/core.py#L381-L385). The `__exit__()` method invokes `close()`, which [sends a message to the server to terminate the connection](https://github.com/aws/amazon-redshift-python-driver/blob/master/redshift_connector/core.py#L1198).

Does this address your ask? If not, please let me know what else you'd like to see :)

**Comment by WillAyd** [comment]
Hey @Brooke-white this is great and actually perfect. Thanks for bringing to my attention - I didn’t look through the code but only checked the documentation on pages like this, where the context manager is not being used:

https://aws-data-wrangler.readthedocs.io/en/2.4.0-docs/stubs/awswrangler.redshift.connect.html

I can push a PR later to improve the docs for that

**Comment by WillAyd** [comment]
@daturkel I can't speak for the intentions of redshift specifically, but as far as PEP 249 goes there is no requirement for drivers to implement what you've described. From my own experience across various drivers you are better served to commit explicitly if using the library directly

sqlalchemy provides a separate `.begin()` context manager based off of the connection which may be what you are after

https://docs.sqlalchemy.org/en/20/core/connections.html#begin-once

**Comment by daturkel** [comment]
@WillAyd thanks for the quick response. Manual committing will be fine for my use case. And yeah I think both sqlalchemy and psycopg do this a bit differently, but the context manager representing a connection rather than a transaction seems reasonable.
