### ISSUE TITLE
Unable to escape reserved word on cursor create table statement

### ISSUE THREAD

**Issue by vfrank66** [aws/amazon-redshift-python-driver#93]
## Driver version

2.0.905

## Redshift version

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.36224	

## Client Operating System

Lambda -x86_64

## Python version

python3.7

## Table schema

```sql
CREATE TABLE IF NOT EXISTS test_table (
  hash_value varchar(255),
  "system" varchar(255),
  value int
)
```

Other create table statements that also fail:
```sql
CREATE TABLE IF NOT EXISTS test_table (
  hash_value varchar(255),
  \ \ "system\\" varchar(255),
  value int
) 

CREATE TABLE IF NOT EXISTS test_table (
  hash_value varchar(255),
  _system varchar(255),
  value int
) 

CREATE TABLE IF NOT EXISTS test_table (
  hash_value varchar(255),
  "system" varchar(255),
  value int
)
```

## Problem description

1. Expected behaviour:
2. Actual behaviour:
3. Error message/stack trace:
4. Any other details that can be helpful:

1. This should create a table as it does in the console. 
2. Instead this throws a error on at the reserved word
3 

Error example 1:
{'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "system"', 'P': '172', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '714', 'R': 'yyerror'}

Error example 2:
{'S': 'ERROR', 'C': '42601', 'M': 'syntax error at or near "\\"', 'P': '214', 'F': '/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', 'L': '714', 'R': 'yyerror'}
Traceback (most recent call last):
File "/opt/python/lib/python3.7/site-packages/redshift_connector/core.py", line 1108, in execute
ps = cache["ps"][key]
KeyError: ('CREATE TABLE IF NOT EXISTS test_table ( hash_value varchar(255),\n  \\\\"system\\\\" varchar(255),\n                 value int', ())

## Reproduction code

```python
con: redshift_connector.Connection = redshift_connector.Connection(
    ...
) 
query="""
CREATE TABLE IF NOT EXISTS test_table (
  hash_value varchar(255),
  "system" varchar(255),
  value int
)"""
with con.cursor() as cursor:
    # logger.info(f"Executing query: \n{query}")
    cursor.execute(query)
```

**Comment by Brooke-white** [comment]
Hi @vfrank66 ,

Thank you for your patience. Are you still experiencing this issue? I was unable reproduce using redshift-connector==2.0.905 and Redshift server version [1.0.36433](https://docs.aws.amazon.com/redshift/latest/mgmt/rs-mgmt-cluster-version-notes.html). My suggestion is to update your Redshift server to the latest version. I don't believe this issue is related to redshift-connector.

Below I've included the script I used to try to reproduce this issue, and its output. I confirmed the table was created, and the specified column names were present using the system tables. Please let me know if you have any questions.

```python
query = """
    CREATE TABLE IF NOT EXISTS github_issue_93 (
      hash_value varchar(255),
      "system" varchar(255),
      value int
    )"""
    with conn.cursor() as cursor:
        cursor.execute(query)
        cursor.execute("select * from svv_all_tables where schema_name='public' and table_name='github_issue_93';")
        result = cursor.fetchall()
        print(result)
        cursor.execute("select * from svv_columns where table_schema='public' and table_name='github_issue_93'")
        result = cursor.fetchall()
        print(result)
```

```
(['dev', 'public', 'github_issue_93', 'TABLE', None, None],)
(['dev', 'public', 'github_issue_93', 'hash_value', 1, None, 'YES', 'character varying', 255, None, None, None, None, None, None, None, None, None, None, None, 'case_sensitive', None, None], ['dev', 'public', 'github_issue_93', 'system', 2, None, 'YES', 'character varying', 255, None, None, None, None, None, None, None, None, None, None, None, 'case_sensitive', None, None], ['dev', 'public', 'github_issue_93', 'value', 3, None, 'YES', 'integer', None, 32, 2, 0, None, None, None, None, None, None, None, None, None, None, None])
```

Additionally, when using the following query, the create statement executed successfully. 
```
CREATE TABLE IF NOT EXISTS test_table (
  hash_value varchar(255),
  _system varchar(255),
  value int
) 
```
