### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)

### ISSUE THREAD

**Issue by akrymskiy** [aws/amazon-redshift-python-driver#96]
## Driver version
2.0.905

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.36926

## Client Operating System
Docker amazonlinux 2.0.20220316.0 on Windows 11 (WSL2)r

## Python version
3.8

## Table schema
public

## Problem description
1. Expected behaviour: UNLOAD sql completes successfully and control is returned from the driver
2. Actual behaviour: UNLOAD operation completes (all expected files are in S3), but driver crashes before returning from connection.run method
3. Error message/stack trace:
Traceback (most recent call last):
  File "archival_redshift.py", line 165, in <module>
    conn.run(sql)
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/core.py", line 1169, in run
    self._run_cursor.execute(sql, params, stream=stream)
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/cursor.py", line 231, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/core.py", line 1763, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/core.py", line 1945, in handle_messages
    code, data_len = ci_unpack(self._read(5))
struct.error: unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/core.py", line 1611, in execute
    ps = cache["ps"][key]
KeyError: ("\n\t\t\t\tinsert into\n\t\t\t\tpublic.archival_output_test\n\t\t\t\tvalues\n\t\t\t\t(3, 'raw', 'master_chat', 0, :error_msg, :lower_bound, '2022-02-04', null, null, current_timestamp);\n\t\t\t\t", ((705, 0, <function text_out at 0x7f7fccd9bdc0>), (-1, 1, <function null_send at 0x7f7fccd96d30>)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "archival_redshift.py", line 184, in <module>
    conn.run(f"""
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/core.py", line 1169, in run
    self._run_cursor.execute(sql, params, stream=stream)
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/cursor.py", line 231, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/core.py", line 1681, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib64/python3.8/site-packages/redshift_connector/core.py", line 1945, in handle_messages
    code, data_len = ci_unpack(self._read(5))
struct.error: unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)

4. Any other details that can be helpful: This completes successfully if UNLOADing less data, so maybe the connection is timing out being dropped?

**Comment by akrymskiy** [comment]
`""" Data Archival Project Redshift Instances """
# Standard Imports
from datetime import date, datetime, timedelta
import os
from pathlib import Path
import re

# Specialized Imports
import boto3
from dotenv import load_dotenv
from dateutil.relativedelta import relativedelta
import redshift_connector

# Loads .env file
load_dotenv(dotenv_path=Path(__file__).parent.joinpath('.env'))

BACKUP_BUCKET = 'cf-db-archive01'

# Initialize boto3
s3_client = boto3.client('s3')
list_paginator = s3_client.get_paginator('list_objects_v2')

def get_latest_prefix(s3_bucket, s3_prefix):
	"""Gets the last/most-recent prefix"""
	response_iterator = list_paginator.paginate(Bucket=s3_bucket, Delimiter='/', Prefix=s3_prefix)
	last_prefix = None
	for page in response_iterator:
		if 'CommonPrefixes' in page:
			last_prefix = page['CommonPrefixes'][-1]['Prefix']

	if last_prefix:
		print(last_prefix)
		regex = re.search(f'{partition_col}=([0-9]{{4}}-[0-9]{{2}}-[0-9]{{2}})', last_prefix)
		return datetime.strptime(regex.group(1), '%Y-%m-%d').date()

def seconds_to_period_string(sec):
	"""Human readable time period"""
	if not sec:
		return 'under 1 sec'

	days, reminder = divmod(sec, 60 * 60 * 24)
	hours, reminder = divmod(reminder, 60 * 60)
	minutes, seconds = divmod(reminder, 60)

	return (
		(f"{int(days)}d " if days else '') +
		(f"{int(hours)}h " if hours else '') +
		(f"{int(minutes)}m " if minutes else '') +
		(f"{seconds:.2f}s " if seconds else '')
	)

# Metadata Table config
with redshift_connector.connect(
	host=os.getenv('rs_host'),
	database=os.getenv('rs_database'),
	user=os.getenv('rs_user'),
	password=os.getenv('rs_password')
) as conn:
	conn.autocommit = True

	# set metadata as list of dictionaries
	table_metadata = {}

	# Query metadata table
	for table in conn.run('select * from public.archival_test;'):
		table_metadata[f'{table[1]}.{table[2]}'] = {
			'archive_id': table[0],
			'schema_name': table[1] if table[1] != 'raw' else f"{table[1]}",
			'table_name': table[2],
			'enabled': table[3],
			'backup_only': table[4],
			'except_cols': table[5] if table[5] else [],
			'hash_cols': table[6] if table[6] else [],
			'retention_period': table[7],
			'filter_col': table[8],
			'partition_col': table[9]
		}

	# copy unload each table in archival_test
	for fqtn, table_meta in table_metadata.items():
		print(f'Archiving `{fqtn}`')

		# set reusable variables
		archive_id = table_meta['archive_id']
		schema_name = table_meta['schema_name']
		table_name = table_meta['table_name']
		retention_period = table_meta['retention_period']
		filter_col = table_meta['filter_col']
		partition_col = table_meta['partition_col']
		cluster_id = os.getenv('rs_host').split('.')[0]
		s3_location_prefix = f"archive/redshift/{cluster_id}/{schema_name}/{table_name}/"

		# set search path
		print('Setting `search_path`')
		conn.run(f'set search_path to public, "{schema_name}";')

		sql = None
		try:
			# generate list of table columns
			print('Querying column meta-data')
			table_columns = conn.run(f"""
			select "column"
			from pg_table_def
			where schemaname = '{schema_name}'
			and tablename = '{table_name}';
			""")

			columns_list = []

			for col in table_columns:
				if col[0] in table_meta.get('except_cols', []):
					continue
				elif col[0] in table_meta.get('hash_cols', []):
					columns_list.append(f'md5("{col[0]}") "{col[0]}"')
				else:
					columns_list.append(f"{col[0]}")

			# calculate timestamp from DB here and insert into query
			today_db = conn.run('select current_timestamp;')[0][0].date()

			if not (match := re.match(r'(\d+)([dmy])', retention_period)):
				raise RuntimeError(f'Invalid `retention_period` for {fqtn}')

			retention_period_value = match.group(1)
			retention_period_unit = match.group(2)

			# calculate upper_bound from table 'retention_period'
			if retention_period_unit == 'd':
				upper_bound = today_db - timedelta(days=int(retention_period_value))
			elif retention_period_unit == 'm':
				upper_bound = today_db - relativedelta(month=int(retention_period_value))
			elif retention_period_unit == 'y':
				upper_bound = today_db - relativedelta(year=int(retention_period_value))
			else:
				raise RuntimeError("Could not calculate date filter from table_meta['retention_period']")

			# calculate lower_bound from max S3 pagination?
			lower_bound = get_latest_prefix(BACKUP_BUCKET, s3_location_prefix)
			# ToDo: TESTING Remove!
			# lower_bound = date(2022, 1, 31)

			# set date_filter for query
			if lower_bound:
				date_filter = f"{filter_col} > ''{lower_bound.strftime('%Y-%m-%d')}'' and {filter_col} < ''{upper_bound}''"
			else:
				date_filter = f"{filter_col} <= ''{upper_bound.strftime('%Y-%m-%d')}''"

			start_time = datetime.now()
			print(f'Unloading data for {fqtn} ({lower_bound} - {upper_bound}]')

			# Copy Unload Query
			sql = f"""
				unload(
				'select {','.join(columns_list)}
				from "{schema_name}".{table_name}
				where {date_filter}')
				to 's3://{BACKUP_BUCKET}/{s3_location_prefix}'
				iam_role 'arn:aws:iam::095308103177:role/DW_Redshift_CopyUnload'
				json
				partition by ({partition_col})
				allowoverwrite
				parallel off
				bzip2;
			"""
			conn.run(sql)
			print(sql)
			print(datetime.now() - start_time)
			unload_duration = int((datetime.now() - start_time).total_seconds())

			print(f'Completed UNLOAD query in {seconds_to_period_string(unload_duration)}')

			# insert into activity_table			
			conn.run(f"""
				insert into
				public.archival_output_test
				values
				({archive_id}, '{schema_name}', '{table_name}', 1, null, :lower_bound, '{upper_bound}', pg_last_unload_count(), {unload_duration}, current_timestamp);
				""",
				lower_bound=lower_bound
			)
			print('Complete Insert Query')

		except Exception as e:
			conn.run(f"""
				insert into
				public.archival_output_test
				values
				({archive_id}, '{schema_name}', '{table_name}', 0, :error_msg, :lower_bound, '{upper_bound}', null, null, current_timestamp);
				""",
				error_msg=f'{str(e)}\nSQL:\n{sql}',
				lower_bound=lower_bound
			)
			print(f"Copy Unload failed for {fqtn}: {e}")

		print('--ARCHIVING COMPLETE--')
`

**Comment by Brooke-white** [comment]
Hey @akrymskiy ,

Thanks for reaching out and providing these details. 

> This completes successfully if UNLOADing less data, so maybe the connection is timing out being dropped?

I think this could be the case here. By default, the socket used for communication with the Redshift cluster has no timeout. As such, I'd recommend to read about [WLM timeout](https://docs.aws.amazon.com/redshift/latest/dg/cm-c-defining-query-queues.html#wlm-timeout) to see if this applies to your Redshift cluster's configuration, then try setting [statement_timeout](https://docs.aws.amazon.com/redshift/latest/dg/r_statement_timeout.html) (e.g. `set statement_timeout to 9;`), if applicable, prior to executing the unload operation. 

> If WLM timeout (max_execution_time) is also specified as part of a WLM configuration, the lower of statement_timeout and max_execution_time is used. [ref](https://docs.aws.amazon.com/redshift/latest/dg/r_statement_timeout.html)

**Comment by Brooke-white** [comment]
A side note -- I assume you have reason for disabling parallelization for the `UNLOAD` statement, but if not it could be worth reading about the [impact of PARALLEL on UNLOAD performance](https://docs.aws.amazon.com/redshift/latest/dg/t_Unloading_tables.html).

**Comment by akrymskiy** [comment]
Thanks for responding @Brooke-white. There is no WLM timeout explicitly defined. This code works if executed directly on Python on Windows, but fails with the referenced error when running inside Docker on WSL. Strangely it works correctly when I push this Docker container into ECR and run it on ECS Fargate - which is how it will run in Prod. I suppose there is something in the Docker on WSL that maybe prevents KeepAlives or something of the sorts - since it does work successfully on UNLOADs that are shorter in duration, since this longer one takes ~11 mins.

The PARALLEL is disabled, because we want a predictable filename in the S3, when PARALLEL is enabled the slice/node identifier is added to the final filename, which may cause data-duplication if we are to overwrite existing data.

Is there any way that you can suggest to troubleshoot this further or handle properly? I wanted to catch the error and possibly reconnect, but I suspect that `pg_last_unload_count()` may not work correctly if it is called on a newly established connection...

**Comment by Brooke-white** [comment]
For troubleshooting this issue as well as related issue #97, I'd recommend checking out the following:
- What is written to `stl_error` table for the db user this issue occurs to? Check `error` `context` columns
- If we cut redshift_connector out of the equation, can a long running statement be run using CLI tools like `psql` or `rsql` inside Docker WSL? 
- Additionally, if we cut Redshift out also, does this issue occur when doing something like opening a long telnet session?
- If you restart Docker WSL does the issue still occur?
- Is there any tcp timeout setting for Docker WSL? If so, can it be increased?


Some resources I found when googling that may (or may not) be worth taking a look at if you haven't already
- https://stackoverflow.com/questions/65554661/wsl2-docker-keep-alive-bug-in-tcp-stack
- https://stackoverflow.com/questions/68639603/inactive-tcp-sockets-disconnecting-in-docker-for-windows-wsl-2


I ran the following tests on Amazon Linux 2 and Mac OS but was unable to reproduce the issue. 

1. Long running query

```python
with redshift_connector.connect(
...
) as conn:
    with conn.cursor() as cursor:
        print('create fn')
        cursor.execute('''CREATE OR REPLACE FUNCTION janky_sleep (x float) RETURNS bool IMMUTABLE as $$
    from time import sleep
    sleep(x)
    return True
$$ LANGUAGE plpythonu;
''')
        import time
        start = time.time()
        print(start)
        # sleep for 10 min
        cursor.execute('select janky_sleep(600.0);') # 10 minutes
        end = time.time()
        print(end - start)
```

2. Large UNLOAD to s3 of table holding ~22GB of data. On Mac OS this operation took ~32 minutes. On Amazon Linux2 this operation took ~30 minutes.

```
SELECT database, "table", size, tbl_rows FROM SVV_TABLE_INFO order by size desc limit 1;

database,table,size,tbl_rows
dev,large_test,19288,805396224
```

```python
with redshift_connector.connect(
...
) as conn:
    with conn.cursor() as cursor:
cursor.execute("select count(*) from large_test")
        result = cursor.fetchone()
        print("rows: ", result)
        import time
        start = time.time()
        print("start", start)
        cursor.execute('''unload ('select * from large_test')
to 's3://my-test-bucket/foo/macos/'
iam_role 'arn:aws:iam::xxxxxx:role/myRedshiftRole';''')
        print("end", time.time())
```

I will run this same test on Windows Server 2019, but my gut feeling here is that this issue may be related to the Docker instance.

**Comment by Brooke-white** [comment]
following up on this, are you still seeing this issue?

**Comment by Brooke-white** [comment]
closing as we haven't heard back. feel free to re-open this, or a new issue if this pops up again.

**Comment by athrpf** [comment]
I am seeing exactly this issue using the redshift python connector from a regular python 3.10 installation of v2.0.911 on linux (no docker). The query raises an exception with exactly the same error message as in the title after pretty much exactly 10 minutes. However, the query seems to continue running in the background, and finishes writing to parquet after about 2 hours.

This problem is reproducible on multiple machines with the python redshift connector, but not reproducible when using jodbc or running the query in a gui (e.g. DataGrip).
