### ISSUE TITLE
TCPKeepAlive during unload does not keep connection alive 

### ISSUE THREAD

**Issue by georgewilson23** [aws/amazon-redshift-python-driver#97]
## Driver version

2.0.905
## Redshift version

 Redshift 1.0.36224

## Client Operating System

Windows Server 2019

## Python version

3.9
## Problem description

1. Expected behaviour: TCP keep alive maintains connections on client 
2. Actual behaviour: UNLOAD begins and after ~5 minutes closes due to timeout. All data is eventually written asynchronously without allowing the script to confirm the action is complete.
3. Error message/stack trace:
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

4. Any other details that can be helpful: 
I believe that the azure machine I am using to run this code has a timeout after 5 minutes. The documentation suggests using TCP keep alive to prevent a timeout. Nevertheless, explicitly setting tcp_keepalive = True did not alleviate this issue.

## Python Driver trace logs

  File "..\main.py", line 187, in redshift_unload
    cursor.execute(unload_script)
  File "..\site-packages\redshift_connector\cursor.py", line 211, in execute
    self._c.execute(self, operation, args)
  File "..\site-packages\redshift_connector\core.py", line 1279, in execute
    self.handle_messages(cursor)
  File "..\site-packages\redshift_connector\core.py", line 1358, in handle_messages
    code, data_len = ci_unpack(self._read(5))
  File "C:\Program Files\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)

## Reproduction code

n/a, requires unload command of duration 5+ minutes

**Comment by Brooke-white** [comment]
Hi @georgewilson23 

Can the timeout on the Azure machine be increased? I would start with trying this.

I'll be closing this issue in favor of related issue #96 where I've posted some troubleshooting recommendations.
